<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace TheCodeBunny\eBayApi\BulkDataExchange\Services;

class BulkDataExchangeService extends \TheCodeBunny\eBayApi\BulkDataExchange\Services\BulkDataExchangeBaseService
{
    const API_VERSION = '1.5.0';

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\CreateUploadJobRequest $request
     * @return \TheCodeBunny\eBayApi\BulkDataExchange\Types\CreateUploadJobResponse
     */
    public function createUploadJob(\TheCodeBunny\eBayApi\BulkDataExchange\Types\CreateUploadJobRequest $request)
    {
        return $this->createUploadJobAsync($request)->wait();
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\CreateUploadJobRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createUploadJobAsync(\TheCodeBunny\eBayApi\BulkDataExchange\Types\CreateUploadJobRequest $request)
    {
        return $this->callOperationAsync(
            'createUploadJob',
            $request,
            '\TheCodeBunny\eBayApi\BulkDataExchange\Types\CreateUploadJobResponse'
        );
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\StartUploadJobRequest $request
     * @return \TheCodeBunny\eBayApi\BulkDataExchange\Types\StartUploadJobResponse
     */
    public function startUploadJob(\TheCodeBunny\eBayApi\BulkDataExchange\Types\StartUploadJobRequest $request)
    {
        return $this->startUploadJobAsync($request)->wait();
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\StartUploadJobRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function startUploadJobAsync(\TheCodeBunny\eBayApi\BulkDataExchange\Types\StartUploadJobRequest $request)
    {
        return $this->callOperationAsync(
            'startUploadJob',
            $request,
            '\TheCodeBunny\eBayApi\BulkDataExchange\Types\StartUploadJobResponse'
        );
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\AbortJobRequest $request
     * @return \TheCodeBunny\eBayApi\BulkDataExchange\Types\AbortJobResponse
     */
    public function abortJob(\TheCodeBunny\eBayApi\BulkDataExchange\Types\AbortJobRequest $request)
    {
        return $this->abortJobAsync($request)->wait();
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\AbortJobRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function abortJobAsync(\TheCodeBunny\eBayApi\BulkDataExchange\Types\AbortJobRequest $request)
    {
        return $this->callOperationAsync(
            'abortJob',
            $request,
            '\TheCodeBunny\eBayApi\BulkDataExchange\Types\AbortJobResponse'
        );
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\GetJobsRequest $request
     * @return \TheCodeBunny\eBayApi\BulkDataExchange\Types\GetJobsResponse
     */
    public function getJobs(\TheCodeBunny\eBayApi\BulkDataExchange\Types\GetJobsRequest $request)
    {
        return $this->getJobsAsync($request)->wait();
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\GetJobsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getJobsAsync(\TheCodeBunny\eBayApi\BulkDataExchange\Types\GetJobsRequest $request)
    {
        return $this->callOperationAsync(
            'getJobs',
            $request,
            '\TheCodeBunny\eBayApi\BulkDataExchange\Types\GetJobsResponse'
        );
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\GetJobStatusRequest $request
     * @return \TheCodeBunny\eBayApi\BulkDataExchange\Types\GetJobStatusResponse
     */
    public function getJobStatus(\TheCodeBunny\eBayApi\BulkDataExchange\Types\GetJobStatusRequest $request)
    {
        return $this->getJobStatusAsync($request)->wait();
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\GetJobStatusRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getJobStatusAsync(\TheCodeBunny\eBayApi\BulkDataExchange\Types\GetJobStatusRequest $request)
    {
        return $this->callOperationAsync(
            'getJobStatus',
            $request,
            '\TheCodeBunny\eBayApi\BulkDataExchange\Types\GetJobStatusResponse'
        );
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\StartDownloadJobRequest $request
     * @return \TheCodeBunny\eBayApi\BulkDataExchange\Types\StartDownloadJobResponse
     */
    public function startDownloadJob(\TheCodeBunny\eBayApi\BulkDataExchange\Types\StartDownloadJobRequest $request)
    {
        return $this->startDownloadJobAsync($request)->wait();
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\StartDownloadJobRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function startDownloadJobAsync(\TheCodeBunny\eBayApi\BulkDataExchange\Types\StartDownloadJobRequest $request)
    {
        return $this->callOperationAsync(
            'startDownloadJob',
            $request,
            '\TheCodeBunny\eBayApi\BulkDataExchange\Types\StartDownloadJobResponse'
        );
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\CreateRecurringJobRequest $request
     * @return \TheCodeBunny\eBayApi\BulkDataExchange\Types\CreateRecurringJobResponse
     */
    public function createRecurringJob(\TheCodeBunny\eBayApi\BulkDataExchange\Types\CreateRecurringJobRequest $request)
    {
        return $this->createRecurringJobAsync($request)->wait();
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\CreateRecurringJobRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createRecurringJobAsync(\TheCodeBunny\eBayApi\BulkDataExchange\Types\CreateRecurringJobRequest $request)
    {
        return $this->callOperationAsync(
            'createRecurringJob',
            $request,
            '\TheCodeBunny\eBayApi\BulkDataExchange\Types\CreateRecurringJobResponse'
        );
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\DeleteRecurringJobRequest $request
     * @return \TheCodeBunny\eBayApi\BulkDataExchange\Types\DeleteRecurringJobResponse
     */
    public function deleteRecurringJob(\TheCodeBunny\eBayApi\BulkDataExchange\Types\DeleteRecurringJobRequest $request)
    {
        return $this->deleteRecurringJobAsync($request)->wait();
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\DeleteRecurringJobRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteRecurringJobAsync(\TheCodeBunny\eBayApi\BulkDataExchange\Types\DeleteRecurringJobRequest $request)
    {
        return $this->callOperationAsync(
            'deleteRecurringJob',
            $request,
            '\TheCodeBunny\eBayApi\BulkDataExchange\Types\DeleteRecurringJobResponse'
        );
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\GetRecurringJobsRequest $request
     * @return \TheCodeBunny\eBayApi\BulkDataExchange\Types\GetRecurringJobsResponse
     */
    public function getRecurringJobs(\TheCodeBunny\eBayApi\BulkDataExchange\Types\GetRecurringJobsRequest $request)
    {
        return $this->getRecurringJobsAsync($request)->wait();
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\GetRecurringJobsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRecurringJobsAsync(\TheCodeBunny\eBayApi\BulkDataExchange\Types\GetRecurringJobsRequest $request)
    {
        return $this->callOperationAsync(
            'getRecurringJobs',
            $request,
            '\TheCodeBunny\eBayApi\BulkDataExchange\Types\GetRecurringJobsResponse'
        );
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\GetRecurringJobExecutionStatusRequest $request
     * @return \TheCodeBunny\eBayApi\BulkDataExchange\Types\GetRecurringJobExecutionStatusResponse
     */
    public function getRecurringJobExecutionStatus(\TheCodeBunny\eBayApi\BulkDataExchange\Types\GetRecurringJobExecutionStatusRequest $request)
    {
        return $this->getRecurringJobExecutionStatusAsync($request)->wait();
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\GetRecurringJobExecutionStatusRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRecurringJobExecutionStatusAsync(\TheCodeBunny\eBayApi\BulkDataExchange\Types\GetRecurringJobExecutionStatusRequest $request)
    {
        return $this->callOperationAsync(
            'getRecurringJobExecutionStatus',
            $request,
            '\TheCodeBunny\eBayApi\BulkDataExchange\Types\GetRecurringJobExecutionStatusResponse'
        );
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\GetRecurringJobExecutionHistoryRequest $request
     * @return \TheCodeBunny\eBayApi\BulkDataExchange\Types\GetRecurringJobExecutionHistoryResponse
     */
    public function getRecurringJobExecutionHistory(\TheCodeBunny\eBayApi\BulkDataExchange\Types\GetRecurringJobExecutionHistoryRequest $request)
    {
        return $this->getRecurringJobExecutionHistoryAsync($request)->wait();
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\GetRecurringJobExecutionHistoryRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRecurringJobExecutionHistoryAsync(\TheCodeBunny\eBayApi\BulkDataExchange\Types\GetRecurringJobExecutionHistoryRequest $request)
    {
        return $this->callOperationAsync(
            'getRecurringJobExecutionHistory',
            $request,
            '\TheCodeBunny\eBayApi\BulkDataExchange\Types\GetRecurringJobExecutionHistoryResponse'
        );
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\ActivateRecurringJobRequest $request
     * @return \TheCodeBunny\eBayApi\BulkDataExchange\Types\ActivateRecurringJobResponse
     */
    public function activateRecurringJob(\TheCodeBunny\eBayApi\BulkDataExchange\Types\ActivateRecurringJobRequest $request)
    {
        return $this->activateRecurringJobAsync($request)->wait();
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\ActivateRecurringJobRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function activateRecurringJobAsync(\TheCodeBunny\eBayApi\BulkDataExchange\Types\ActivateRecurringJobRequest $request)
    {
        return $this->callOperationAsync(
            'activateRecurringJob',
            $request,
            '\TheCodeBunny\eBayApi\BulkDataExchange\Types\ActivateRecurringJobResponse'
        );
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\SuspendRecurringJobRequest $request
     * @return \TheCodeBunny\eBayApi\BulkDataExchange\Types\SuspendRecurringJobResponse
     */
    public function suspendRecurringJob(\TheCodeBunny\eBayApi\BulkDataExchange\Types\SuspendRecurringJobRequest $request)
    {
        return $this->suspendRecurringJobAsync($request)->wait();
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\SuspendRecurringJobRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function suspendRecurringJobAsync(\TheCodeBunny\eBayApi\BulkDataExchange\Types\SuspendRecurringJobRequest $request)
    {
        return $this->callOperationAsync(
            'suspendRecurringJob',
            $request,
            '\TheCodeBunny\eBayApi\BulkDataExchange\Types\SuspendRecurringJobResponse'
        );
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\AbortRecurringJobExecutionRequest $request
     * @return \TheCodeBunny\eBayApi\BulkDataExchange\Types\AbortRecurringJobExecutionResponse
     */
    public function abortRecurringJobExecution(\TheCodeBunny\eBayApi\BulkDataExchange\Types\AbortRecurringJobExecutionRequest $request)
    {
        return $this->abortRecurringJobExecutionAsync($request)->wait();
    }

    /**
     * @param \TheCodeBunny\eBayApi\BulkDataExchange\Types\AbortRecurringJobExecutionRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function abortRecurringJobExecutionAsync(\TheCodeBunny\eBayApi\BulkDataExchange\Types\AbortRecurringJobExecutionRequest $request)
    {
        return $this->callOperationAsync(
            'abortRecurringJobExecution',
            $request,
            '\TheCodeBunny\eBayApi\BulkDataExchange\Types\AbortRecurringJobExecutionResponse'
        );
    }
}
