<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace TheCodeBunny\eBayApi\ReturnManagement\Types;

/**
 *
 * @property string $globalId
 * @property \TheCodeBunny\eBayApi\ReturnManagement\Types\ReturnResponseHistoryType[] $returnHistory
 * @property \TheCodeBunny\eBayApi\ReturnManagement\Types\RefundInfoType $refundInfo
 * @property \TheCodeBunny\eBayApi\ReturnManagement\Types\ReturnPolicyInfoType $returnPolicy
 * @property \TheCodeBunny\eBayApi\ReturnManagement\Types\ShipmentType $buyerReturnShipment
 * @property \TheCodeBunny\eBayApi\ReturnManagement\Types\ShipmentType[] $shipmentInfo
 * @property \TheCodeBunny\eBayApi\ReturnManagement\Types\CaseIdType $caseId
 */
class ReturnDetailType extends \TheCodeBunny\eBayApi\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'globalId' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'globalId'
        ],
        'returnHistory' => [
            'type' => 'TheCodeBunny\eBayApi\ReturnManagement\Types\ReturnResponseHistoryType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'returnHistory'
        ],
        'refundInfo' => [
            'type' => 'TheCodeBunny\eBayApi\ReturnManagement\Types\RefundInfoType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'refundInfo'
        ],
        'returnPolicy' => [
            'type' => 'TheCodeBunny\eBayApi\ReturnManagement\Types\ReturnPolicyInfoType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'returnPolicy'
        ],
        'buyerReturnShipment' => [
            'type' => 'TheCodeBunny\eBayApi\ReturnManagement\Types\ShipmentType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'buyerReturnShipment'
        ],
        'shipmentInfo' => [
            'type' => 'TheCodeBunny\eBayApi\ReturnManagement\Types\ShipmentType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'shipmentInfo'
        ],
        'caseId' => [
            'type' => 'TheCodeBunny\eBayApi\ReturnManagement\Types\CaseIdType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'caseId'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="http://www.ebay.com/marketplace/returns/v1/services"';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
