<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace TheCodeBunny\eBayApi\Inventory\Types;

/**
 *
 * @property \TheCodeBunny\eBayApi\Inventory\Types\Amount $amount
 * @property string $feeType
 * @property \TheCodeBunny\eBayApi\Inventory\Types\Amount $promotionalDiscount
 */
class Fee extends \TheCodeBunny\eBayApi\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'amount' => [
            'type' => 'TheCodeBunny\eBayApi\Inventory\Types\Amount',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'amount'
        ],
        'feeType' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'feeType'
        ],
        'promotionalDiscount' => [
            'type' => 'TheCodeBunny\eBayApi\Inventory\Types\Amount',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'promotionalDiscount'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
