<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace TheCodeBunny\eBayApi\ProductMetadata\Types;

/**
 *
 * @property \TheCodeBunny\eBayApi\ProductMetadata\Types\URITypeSpecificInformation $uriTypeSpecificInformation
 * @property \TheCodeBunny\eBayApi\ProductMetadata\Types\NumericTypeSpecificInformation $numericTypeSpecificInformation
 * @property \TheCodeBunny\eBayApi\ProductMetadata\Types\MediaTypeSpecificInformation $mediaTypeSpecificInformation
 * @property \TheCodeBunny\eBayApi\ProductMetadata\Types\StringTypeSpecificInformation $stringTypeSpecificInformation
 */
class TypeSpecificInformation extends \TheCodeBunny\eBayApi\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'uriTypeSpecificInformation' => [
            'type' => 'TheCodeBunny\eBayApi\ProductMetadata\Types\URITypeSpecificInformation',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'uriTypeSpecificInformation'
        ],
        'numericTypeSpecificInformation' => [
            'type' => 'TheCodeBunny\eBayApi\ProductMetadata\Types\NumericTypeSpecificInformation',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'numericTypeSpecificInformation'
        ],
        'mediaTypeSpecificInformation' => [
            'type' => 'TheCodeBunny\eBayApi\ProductMetadata\Types\MediaTypeSpecificInformation',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'mediaTypeSpecificInformation'
        ],
        'stringTypeSpecificInformation' => [
            'type' => 'TheCodeBunny\eBayApi\ProductMetadata\Types\StringTypeSpecificInformation',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'stringTypeSpecificInformation'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="http://www.ebay.com/marketplace/marketplacecatalog/v1/services"';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
