<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace TheCodeBunny\eBayApi\Shopping\Types;

/**
 *
 * @property \TheCodeBunny\eBayApi\Shopping\Types\AmountType $InsuranceCost
 * @property \TheCodeBunny\eBayApi\Shopping\Enums\InsuranceOptionCodeType $InsuranceOption
 * @property \TheCodeBunny\eBayApi\Shopping\Types\InternationalShippingServiceOptionType[] $InternationalShippingServiceOption
 * @property \TheCodeBunny\eBayApi\Shopping\Types\SalesTaxType $SalesTax
 * @property string $ShippingRateErrorMessage
 * @property \TheCodeBunny\eBayApi\Shopping\Types\ShippingServiceOptionType[] $ShippingServiceOption
 * @property \TheCodeBunny\eBayApi\Shopping\Types\TaxTableType $TaxTable
 * @property \TheCodeBunny\eBayApi\Shopping\Types\AmountType $InternationalInsuranceCost
 * @property \TheCodeBunny\eBayApi\Shopping\Enums\InsuranceOptionCodeType $InternationalInsuranceOption
 * @property \TheCodeBunny\eBayApi\Shopping\Types\AmountType $CODCost
 * @property string[] $ExcludeShipToLocation
 */
class ShippingDetailsType extends \TheCodeBunny\eBayApi\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'InsuranceCost' => [
            'type' => 'TheCodeBunny\eBayApi\Shopping\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'InsuranceCost'
        ],
        'InsuranceOption' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'InsuranceOption'
        ],
        'InternationalShippingServiceOption' => [
            'type' => 'TheCodeBunny\eBayApi\Shopping\Types\InternationalShippingServiceOptionType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'InternationalShippingServiceOption'
        ],
        'SalesTax' => [
            'type' => 'TheCodeBunny\eBayApi\Shopping\Types\SalesTaxType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SalesTax'
        ],
        'ShippingRateErrorMessage' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ShippingRateErrorMessage'
        ],
        'ShippingServiceOption' => [
            'type' => 'TheCodeBunny\eBayApi\Shopping\Types\ShippingServiceOptionType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'ShippingServiceOption'
        ],
        'TaxTable' => [
            'type' => 'TheCodeBunny\eBayApi\Shopping\Types\TaxTableType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'TaxTable'
        ],
        'InternationalInsuranceCost' => [
            'type' => 'TheCodeBunny\eBayApi\Shopping\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'InternationalInsuranceCost'
        ],
        'InternationalInsuranceOption' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'InternationalInsuranceOption'
        ],
        'CODCost' => [
            'type' => 'TheCodeBunny\eBayApi\Shopping\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'CODCost'
        ],
        'ExcludeShipToLocation' => [
            'type' => 'string',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'ExcludeShipToLocation'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
