<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace TheCodeBunny\eBayApi\BulkDataExchange\Types;

/**
 *
 * @property string $UUID
 * @property \TheCodeBunny\eBayApi\BulkDataExchange\Types\DownloadJobRecurringFilter $downloadJobRecurringFilter
 * @property integer $frequencyInMinutes
 * @property string $downloadJobType
 * @property \TheCodeBunny\eBayApi\BulkDataExchange\Types\MonthlyRecurrence $monthlyRecurrence
 * @property \TheCodeBunny\eBayApi\BulkDataExchange\Types\WeeklyRecurrence $weeklyRecurrence
 * @property \TheCodeBunny\eBayApi\BulkDataExchange\Types\DailyRecurrence $dailyRecurrence
 */
class CreateRecurringJobRequest extends \TheCodeBunny\eBayApi\BulkDataExchange\Types\BaseServiceRequest
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'UUID' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'UUID'
        ],
        'downloadJobRecurringFilter' => [
            'type' => 'TheCodeBunny\eBayApi\BulkDataExchange\Types\DownloadJobRecurringFilter',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'downloadJobRecurringFilter'
        ],
        'frequencyInMinutes' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'frequencyInMinutes'
        ],
        'downloadJobType' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'downloadJobType'
        ],
        'monthlyRecurrence' => [
            'type' => 'TheCodeBunny\eBayApi\BulkDataExchange\Types\MonthlyRecurrence',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'monthlyRecurrence'
        ],
        'weeklyRecurrence' => [
            'type' => 'TheCodeBunny\eBayApi\BulkDataExchange\Types\WeeklyRecurrence',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'weeklyRecurrence'
        ],
        'dailyRecurrence' => [
            'type' => 'TheCodeBunny\eBayApi\BulkDataExchange\Types\DailyRecurrence',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'dailyRecurrence'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="http://www.ebay.com/marketplace/services"';
        }

        if (!array_key_exists(__CLASS__, self::$requestXmlRootElementNames)) {
            self::$requestXmlRootElementNames[__CLASS__] = 'createRecurringJobRequest';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
