<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace TheCodeBunny\eBayApi\Marketing\Types;

/**
 *
 * @property string[] $brands
 * @property string[] $categoryIds
 * @property \TheCodeBunny\eBayApi\Marketing\Enums\CategoryScopeEnum $categoryScope
 * @property string[] $listingConditionIds
 * @property \TheCodeBunny\eBayApi\Marketing\Types\Amount $maxPrice
 * @property \TheCodeBunny\eBayApi\Marketing\Types\Amount $minPrice
 */
class SelectionRule extends \TheCodeBunny\eBayApi\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'brands' => [
            'type' => 'string',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'brands'
        ],
        'categoryIds' => [
            'type' => 'string',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'categoryIds'
        ],
        'categoryScope' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'categoryScope'
        ],
        'listingConditionIds' => [
            'type' => 'string',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'listingConditionIds'
        ],
        'maxPrice' => [
            'type' => 'TheCodeBunny\eBayApi\Marketing\Types\Amount',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'maxPrice'
        ],
        'minPrice' => [
            'type' => 'TheCodeBunny\eBayApi\Marketing\Types\Amount',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'minPrice'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
